/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;


import Controller.UsuarioController;
import Model.Usuario;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jimx
 */
public class FormUsuario extends javax.swing.JPanel {

    private DefaultTableModel dtmUsuarios = new DefaultTableModel();
    private UsuarioController UsuarioCon = new UsuarioController();
    
    
    public FormUsuario() {
        
        initComponents();
       llenarColumna();
        listarUsuarios();
    }
    
    public void llenarColumna()
    {
        dtmUsuarios.addColumn("ID");
        dtmUsuarios.addColumn("USUARIO");
        dtmUsuarios.addColumn("CONTRASEÑA");
        dtmUsuarios.addColumn("TIPO");
        
        
        this.tablaUsuario.setModel(dtmUsuarios);
    }
    
    public void listarUsuarios()
    {
        List<Usuario> lst = UsuarioCon.getAllUsuariosController();
        dtmUsuarios.setNumRows(0);
        for(Usuario x:lst)
        {
            Object[] vector = new Object[4];
            vector[0] = x.getId();
            vector[1] = x.getNombre();
            vector[2] = x.getContraseña();
            vector[3] = x.getTipo();
            dtmUsuarios.addRow(vector);
        }
        tablaUsuario.setModel(dtmUsuarios);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuario = new javax.swing.JTable();
        jPanel3 = new RoundedPanel(15, new Color(204,204,255));
        LAdd = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new RoundedPanel(15, new Color(204,204,255));
        LabelEliminar = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel5 = new RoundedPanel(15, new Color(204,204,255));
        LabelEditar = new javax.swing.JLabel();
        Buscar = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel6 = new RoundedPanel(15, new Color(204,204,255));
        LabelActualizar = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(830, 670));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Candara", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("ADMINISTRADOR");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        tablaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuario);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 1100, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        LAdd.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        LAdd.setForeground(new java.awt.Color(0, 0, 0));
        LAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LAdd.setText("AGREGAR");
        LAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(LAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 230, 40));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 230, 10));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        LabelEliminar.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        LabelEliminar.setForeground(new java.awt.Color(0, 0, 0));
        LabelEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelEliminar.setText("ELIMINAR");
        LabelEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelEliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(LabelEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, 230, 40));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 120, 230, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 230, 10));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        LabelEditar.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        LabelEditar.setForeground(new java.awt.Color(0, 0, 0));
        LabelEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelEditar.setText("EDITAR");
        LabelEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelEditarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(LabelEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 230, 40));

        Buscar.setText("Buscar por nombre...");
        Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarMouseClicked(evt);
            }
        });
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BuscarKeyReleased(evt);
            }
        });
        add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 159, 230, 30));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 230, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 230, 10));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        LabelActualizar.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        LabelActualizar.setForeground(new java.awt.Color(0, 0, 0));
        LabelActualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelActualizar.setText("ACTUALIZAR");
        LabelActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelActualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(LabelActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelActualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 230, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        if (Buscar.getText().equals("Buscar por nombre...")) {
                    Buscar.setText("");
                }
    }//GEN-LAST:event_BuscarActionPerformed

    private void LAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LAddMouseClicked
        FormAddUsuario VistaAdd = new FormAddUsuario();
        
        VistaAdd.setVisible(true);
        
    }//GEN-LAST:event_LAddMouseClicked

    private void LabelEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelEditarMouseClicked
        int msg = JOptionPane.showConfirmDialog(LabelEditar,"Deseas editar el Registro!!!","EDITAR ",JOptionPane.YES_NO_OPTION);
        if (msg == JOptionPane.YES_OPTION)
        {
           Usuario objUsu = new Usuario();
           
           objUsu.setId(tablaUsuario.getValueAt(tablaUsuario.getSelectedRow(),0).toString());
           objUsu.setNombre(tablaUsuario.getValueAt(tablaUsuario.getSelectedRow(),1).toString());
           objUsu.setContraseña(tablaUsuario.getValueAt(tablaUsuario.getSelectedRow(),2).toString());
           objUsu.setTipo(tablaUsuario.getValueAt(tablaUsuario.getSelectedRow(),3).toString());
           
           FormEditarUsuario edit = new FormEditarUsuario();
           edit.PasarObjeto(objUsu);
           edit.setVisible(true);
           
           
        }  
    }//GEN-LAST:event_LabelEditarMouseClicked

    private void tablaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuarioMouseClicked
        
        
        
    }//GEN-LAST:event_tablaUsuarioMouseClicked

    private void LabelActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelActualizarMouseClicked
        listarUsuarios();
    }//GEN-LAST:event_LabelActualizarMouseClicked

    private void LabelEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelEliminarMouseClicked
        
        int msg = JOptionPane.showConfirmDialog(LabelEliminar,"Deseas Eliminar el Registro!!!","Eliminar",JOptionPane.YES_NO_OPTION);
        if (msg == JOptionPane.YES_OPTION)
        {
            Usuario objUsu = new Usuario();
            objUsu.setId(tablaUsuario.getValueAt(tablaUsuario.getSelectedRow(),0).toString());
            UsuarioCon.EliminarUsuarioController(objUsu);
            listarUsuarios();//Actualizar BD
            JOptionPane.showMessageDialog(this,"Registro Eliminado Satisfactoriamente");
        }    
        
    }//GEN-LAST:event_LabelEliminarMouseClicked

    private void BuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarKeyReleased
        Usuario obj = new Usuario();
        obj.setNombre(this.Buscar.getText());
        List<Usuario> lst = UsuarioCon.getBuscarPorNombreController(obj);
        dtmUsuarios.setNumRows(0);
        for(Usuario x:lst)
        {
            Object[] vector = new Object[4];
            vector[0] = x.getId();
            vector[1] = x.getNombre();
            vector[2] = x.getContraseña();
            vector[3] = x.getTipo();
            dtmUsuarios.addRow(vector);
        }
        tablaUsuario.setModel(dtmUsuarios); 
        
        
    }//GEN-LAST:event_BuscarKeyReleased

    private void BuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarMouseClicked
       if (Buscar.getText().equals("Buscar por nombre...")) {
                    Buscar.setText("");
                }
    }//GEN-LAST:event_BuscarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Buscar;
    private javax.swing.JLabel LAdd;
    private javax.swing.JLabel LabelActualizar;
    private javax.swing.JLabel LabelEditar;
    private javax.swing.JLabel LabelEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable tablaUsuario;
    // End of variables declaration//GEN-END:variables

    
    //Clase para panel con esquinas redondeadas
    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        
        
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
        
    }

}
