/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;


import Controller.DoctorController;
import Model.Doctor;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jimx
 */
public class FormDoctor extends javax.swing.JPanel {

    private DefaultTableModel dtmDoctor = new DefaultTableModel();
    private DoctorController DocCon = new DoctorController();
    
    public FormDoctor() {
        
        initComponents();
        llenarColumna();
        listarDoctores();
        
    }
    
    public void llenarColumna()
    {
        dtmDoctor.addColumn("ID");
        dtmDoctor.addColumn("DOCTOR");
        
        dtmDoctor.addColumn("ESPECIALIDAD");
        
        
        this.tablaDoctor.setModel(dtmDoctor);
    }
    
    public void listarDoctores()
    {
        List<Doctor> lst = DocCon.getAllDoctoresController();
        dtmDoctor.setNumRows(0);
        for(Doctor x:lst)
        {
            Object[] vector = new Object[3];
            vector[0] = x.getId();
            vector[1] = x.getNombre();
            vector[2] = x.getEspecialidad();
            dtmDoctor.addRow(vector);
        }
        tablaDoctor.setModel(dtmDoctor);
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDoctor = new javax.swing.JTable();
        jPanel3 = new RoundedPanel(15, new Color(204,204,255));
        LabelAdd = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new RoundedPanel(15, new Color(204,204,255));
        LabelEdit = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel5 = new RoundedPanel(15, new Color(204,204,255));
        LabelEliminar = new javax.swing.JLabel();
        Buscar = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel6 = new RoundedPanel(15, new Color(204,204,255));
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(830, 670));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaDoctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaDoctor);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 1100, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        LabelAdd.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        LabelAdd.setForeground(new java.awt.Color(0, 0, 0));
        LabelAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAdd.setText("AGREGAR");
        LabelAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(LabelAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 230, 40));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 230, 10));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        LabelEdit.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        LabelEdit.setForeground(new java.awt.Color(0, 0, 0));
        LabelEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelEdit.setText("EDITAR");
        LabelEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelEditMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(LabelEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 230, 40));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 230, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, 230, 10));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        LabelEliminar.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        LabelEliminar.setForeground(new java.awt.Color(0, 0, 0));
        LabelEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelEliminar.setText("ELIMINAR");
        LabelEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelEliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(LabelEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 80, 230, 40));

        Buscar.setText("Buscar por nombre...");
        Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarMouseClicked(evt);
            }
        });
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BuscarKeyReleased(evt);
            }
        });
        add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 159, 230, 30));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 230, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 230, 10));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ACTUALIZAR");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 230, 40));

        jLabel1.setFont(new java.awt.Font("Candara", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("DOCTORES");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        listarDoctores();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void LabelEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelEditMouseClicked
        int msg = JOptionPane.showConfirmDialog(LabelEdit,"Deseas editar el Registro!!!","EDITAR ",JOptionPane.YES_NO_OPTION);
        if (msg == JOptionPane.YES_OPTION)
        {
           Doctor objDoc = new Doctor();
           
           objDoc.setId(tablaDoctor.getValueAt(tablaDoctor.getSelectedRow(),0).toString());
           objDoc.setNombre(tablaDoctor.getValueAt(tablaDoctor.getSelectedRow(),1).toString());
           objDoc.setEspecialidad(tablaDoctor.getValueAt(tablaDoctor.getSelectedRow(),2).toString());
           
           
           
           FormEditarDoctor edit = new FormEditarDoctor();
           edit.PasarObjeto(objDoc);
           edit.setVisible(true);
           
           
        }  
    }//GEN-LAST:event_LabelEditMouseClicked

    private void LabelAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelAddMouseClicked
        FormAddDoctor VistaAdd = new FormAddDoctor();
        
        VistaAdd.setVisible(true);
       
    }//GEN-LAST:event_LabelAddMouseClicked

    private void LabelEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelEliminarMouseClicked
        int msg = JOptionPane.showConfirmDialog(LabelEliminar,"Deseas Eliminar el Registro!!!","Eliminar",JOptionPane.YES_NO_OPTION);
        if (msg == JOptionPane.YES_OPTION)
        {
           Doctor objDoc = new Doctor();
            objDoc.setId(tablaDoctor.getValueAt(tablaDoctor.getSelectedRow(),0).toString());
            DocCon.EliminarDoctorController(objDoc);
            listarDoctores();//Actualizar BD
            JOptionPane.showMessageDialog(this,"Registro Eliminado Satisfactoriamente");
        }   
    }//GEN-LAST:event_LabelEliminarMouseClicked

    private void BuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarKeyReleased
        Doctor obj = new Doctor();
        obj.setNombre(this.Buscar.getText());
        List<Doctor> lst = DocCon.getBuscarDoctorController(obj);
        dtmDoctor.setNumRows(0);
        for(Doctor x:lst)
        {
            Object[] vector = new Object[3];
            vector[0] = x.getId();
            vector[1] = x.getNombre();
            
            vector[2] = x.getEspecialidad();
            dtmDoctor.addRow(vector);
        }
        tablaDoctor.setModel(dtmDoctor); 
    }//GEN-LAST:event_BuscarKeyReleased

    private void BuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarMouseClicked
        if (Buscar.getText().equals("Buscar por nombre...")) {
                    Buscar.setText("");
                }
    }//GEN-LAST:event_BuscarMouseClicked

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        if (Buscar.getText().equals("Buscar por nombre...")) {
                    Buscar.setText("");
                }
    }//GEN-LAST:event_BuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Buscar;
    private javax.swing.JLabel LabelAdd;
    private javax.swing.JLabel LabelEdit;
    private javax.swing.JLabel LabelEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable tablaDoctor;
    // End of variables declaration//GEN-END:variables

    
    //Clase para panel con esquinas redondeadas
    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        
        
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
        
    }

}
