/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;


import Controller.PacienteController;
import Model.Paciente;
import Model.Paciente;
import Model.Paciente;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jimx
 */
public class FormPaciente extends javax.swing.JPanel {

    private DefaultTableModel dtmPaciente = new DefaultTableModel();
    private PacienteController pacCon = new PacienteController();
    
    public FormPaciente() {
        
        initComponents();
        llenarColumna();
        listarPacientes();
        
    }
    
     public void llenarColumna()
    {
        dtmPaciente.addColumn("ID");
        dtmPaciente.addColumn("NOMBRE");
        
        dtmPaciente.addColumn("APELLIDOS");
        dtmPaciente.addColumn("EDAD");
        dtmPaciente.addColumn("DNI");
        dtmPaciente.addColumn("SEXO");
        
        
        this.tablaPaciente.setModel(dtmPaciente);
    }
   
     
     public void listarPacientes()
    {
        List<Paciente> lst = pacCon.getAllPacientesController();
        dtmPaciente.setNumRows(0);
        for(Paciente x:lst)
        {
            Object[] vector = new Object[6];
            vector[0] = x.getId();
            vector[1] = x.getNombre();
            vector[2] = x.getApellidos();
            vector[3] = x.getEdad();
            vector[4] = x.getDni();
            vector[5] = x.getSexo();
           
            dtmPaciente.addRow(vector);
        }
        tablaPaciente.setModel(dtmPaciente);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new RoundedPanel(15, new Color(204,204,255));
        LabelNuevo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPaciente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new RoundedPanel(15, new Color(204,204,255));
        LabelEditar = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new RoundedPanel(15, new Color(204,204,255));
        LabelEliminar = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel5 = new RoundedPanel(15, new Color(204,204,255));
        LabelActualizar = new javax.swing.JLabel();
        Buscar = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(830, 670));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        LabelNuevo.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        LabelNuevo.setForeground(new java.awt.Color(0, 0, 0));
        LabelNuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNuevo.setText("NUEVO PACIENTE");
        LabelNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelNuevoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(LabelNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 230, 40));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 230, 10));

        tablaPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaPaciente);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 1100, -1));

        jLabel1.setFont(new java.awt.Font("Candara", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("PACIENTE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        LabelEditar.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        LabelEditar.setForeground(new java.awt.Color(0, 0, 0));
        LabelEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelEditar.setText("EDITAR PACIENTE");
        LabelEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelEditarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(LabelEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 230, 40));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 230, 10));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        LabelEliminar.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        LabelEliminar.setForeground(new java.awt.Color(0, 0, 0));
        LabelEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelEliminar.setText("ELIMINAR PACIENTE");
        LabelEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelEliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(LabelEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 70, 230, 40));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, 230, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 230, 10));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        LabelActualizar.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        LabelActualizar.setForeground(new java.awt.Color(0, 0, 0));
        LabelActualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelActualizar.setText("ACTUALIZAR");
        LabelActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelActualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(LabelActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelActualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 230, -1));

        Buscar.setText("Buscar por nombre...");
        Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarMouseClicked(evt);
            }
        });
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BuscarKeyReleased(evt);
            }
        });
        add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 159, 230, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarMouseClicked
        if (Buscar.getText().equals("Buscar por nombre...")) {
            Buscar.setText("");
        }
    }//GEN-LAST:event_BuscarMouseClicked

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        if (Buscar.getText().equals("Buscar por nombre...")) {
            Buscar.setText("");
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void BuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarKeyReleased
         Paciente obj = new Paciente();
        obj.setNombre(this.Buscar.getText());
        List<Paciente> lst = pacCon.getBuscarPacienteController(obj);
        dtmPaciente.setNumRows(0);
        for(Paciente x:lst)
        {
            Object[] vector = new Object[6];
            vector[0] = x.getId();
            vector[1] = x.getNombre();
            vector[2] = x.getApellidos();
            vector[3] = x.getEdad();
            vector[4] = x.getDni();
            vector[5] = x.getSexo();
            
            
            dtmPaciente.addRow(vector);
        }
        tablaPaciente.setModel(dtmPaciente); 
    }//GEN-LAST:event_BuscarKeyReleased

    private void LabelNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelNuevoMouseClicked
        FormAddPaciente VistaAdd = new FormAddPaciente();
        
        VistaAdd.setVisible(true);
    }//GEN-LAST:event_LabelNuevoMouseClicked

    private void LabelActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelActualizarMouseClicked
       listarPacientes();
    }//GEN-LAST:event_LabelActualizarMouseClicked

    private void LabelEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelEditarMouseClicked
        
        int msg = JOptionPane.showConfirmDialog(LabelEditar,"Deseas editar el Registro!!!","EDITAR ",JOptionPane.YES_NO_OPTION);
        if (msg == JOptionPane.YES_OPTION)
        {
           Paciente objDoc = new Paciente();
           
           objDoc.setId(tablaPaciente.getValueAt(tablaPaciente.getSelectedRow(),0).toString());
           objDoc.setNombre(tablaPaciente.getValueAt(tablaPaciente.getSelectedRow(),1).toString());
           objDoc.setApellidos(tablaPaciente.getValueAt(tablaPaciente.getSelectedRow(),2).toString());
           objDoc.setEdad(tablaPaciente.getValueAt(tablaPaciente.getSelectedRow(),3).toString());
           objDoc.setDni(tablaPaciente.getValueAt(tablaPaciente.getSelectedRow(),4).toString());
           objDoc.setSexo(tablaPaciente.getValueAt(tablaPaciente.getSelectedRow(),5).toString());
           
           
           
           FormEditPaciente edit = new FormEditPaciente();
           edit.PasarObjeto(objDoc);
           edit.setVisible(true);
           
           
        }  
         
    }//GEN-LAST:event_LabelEditarMouseClicked

    private void LabelEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelEliminarMouseClicked
        
         int msg = JOptionPane.showConfirmDialog(LabelEliminar,"Deseas Eliminar el Registro!!!","Eliminar",JOptionPane.YES_NO_OPTION);
        if (msg == JOptionPane.YES_OPTION)
        {
           Paciente objPac = new Paciente();
            objPac.setId(tablaPaciente.getValueAt(tablaPaciente.getSelectedRow(),0).toString());
            pacCon.EliminarPacienteController(objPac);
            listarPacientes();//Actualizar BD
            JOptionPane.showMessageDialog(this,"Registro Eliminado Satisfactoriamente");
        }   
    }//GEN-LAST:event_LabelEliminarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Buscar;
    private javax.swing.JLabel LabelActualizar;
    private javax.swing.JLabel LabelEditar;
    private javax.swing.JLabel LabelEliminar;
    private javax.swing.JLabel LabelNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable tablaPaciente;
    // End of variables declaration//GEN-END:variables

    
    //Clase para panel con esquinas redondeadas
    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        
        
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
        
    }

}
